SwitchOMatic/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SwitchOMatic.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "It's the Bestest. No Really.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

SwitchOMatic/Controllers/SwitchOMaticController.cs
using SwitchOMatic.Models;
using SwitchOMatic.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SwitchOMatic.Controllers
{
    public class SwitchOMaticController : Controller
    {
        private readonly ISwitchOMaticService _switchOMaticService;
        private readonly ILoggingService _loggingService;

        public SwitchOMaticController(ISwitchOMaticService switchOMaticService, ILoggingService loggingService)
        {
            _switchOMaticService = switchOMaticService;
            _loggingService = loggingService;
        }

        // GET: SwitchOMatic
        public ActionResult Index()
        {
            return View(_switchOMaticService.GetResultsList());
        }

        // GET: SwitchOMatic/Details/5
        public ActionResult Details(int id)
        {
            var model = new SwitchOMaticViewModel(_switchOMaticService.GetResultsById(id));
            return View(model);
        }

        // GET: SwitchOMatic/Create
        public ActionResult Run()
        {
            return View("Details",new SwitchOMaticViewModel());
        }

        // POST: SwitchOMatic/Create
        [HttpPost]
        public ActionResult Run(SwitchOMaticSettings settings)
        {
            var timestart = DateTime.Now;

            try
            {                
               var results = _switchOMaticService.Run(settings);

                results.RunTime = DateTime.Now - timestart;

                return View("Details",new SwitchOMaticViewModel(results));
            }
            catch (Exception ex)
            {
                string errorMessage = string.Format("Uh oh. An error occurred: {0}", ex.Message);
                ViewBag.errorMessage = errorMessage;
                _loggingService.CreateLogEntry(DateTime.Now, "LoggingService", "An error occurred during Scenario save", errorMessage,"user@user.com"); 
                return View("Details",new SwitchOMaticViewModel());
            }
        }

       

       
    }
}

SwitchOMatic/Views/Home/About.cshtml
@{
    ViewBag.Title = "About SwitchOMatic";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>SwitchOMatic is a next generation modeling tool for modeling the age old question of how many people can turn on or off how many lights and what are the results?.</p>
<p>You can hire a ton of people and wire up a bunch of lights; or you can use crack open a beer and use SwitchOMatic!</p>

SwitchOMatic/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

SwitchOMatic/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Switch-O-Matic</h1>
    <p class="lead">Switch O Matic is a great tool for imagining stuffing people and lights into a room and modeling the mayhem that ensues!</p>
    <p><a href="@Url.Action("Run", "SwitchOMatic")" class="btn btn-primary btn-lg">Try It &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
           SwitchOMatic lets you get results without spending money on lights or hiring people.
        </p>
        <p><a class="btn btn-default" href="@Url.Action("About","Home")">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more results</h2>
        <p>Model results with up to 100,000 lights and 100,000 people. That's a lot of energy and people's time saved!.</p>
        <p><a class="btn btn-default" href="@Url.Action("Run","SwitchOMatic")">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>See past results</h2>
        <p>Don't waste time re-running past results. You can examine past runs in the results list..</p>
        <p><a class="btn btn-default" href="@Url.Action("Index","SwitchOMatic")">Learn more &raquo;</a></p>
    </div>
</div>